// Tauri API imports with safe browser fallback and premium mocks for full offline/browser previewing
export let invoke = async (cmd: string, args?: any): Promise<any> => {
  console.log(`Mock calling command: ${cmd}`, args);
  
  // High fidelity mock responses for normal browser runtimes
  if (cmd === 'scan_projects') {
    return Promise.resolve([
      { title: 'Quantum Physics Prep', relative_path: '01_Projects/Quantum Physics Prep.md', category: 'Projects' },
      { title: 'Artificial Intelligence Thesis', relative_path: '01_Projects/Artificial Intelligence Thesis.md', category: 'Projects' },
      { title: 'Healthy Habits System', relative_path: '01_Projects/Healthy Habits System.md', category: 'Projects' }
    ]);
  }
  
  if (cmd === 'get_project_tree') {
    const title = args.projectTitle;
    const deps = title.includes('Quantum') 
      ? [
          { title: 'Schrodinger Equations', relative_path: '03_Resources/Schrodinger Equations.md', category: 'Resources', resolved_path: '' },
          { title: 'Thermodynamics Area', relative_path: '02_Areas/Thermodynamics Area.md', category: 'Areas', resolved_path: '' },
          { title: 'Dead Link Note', relative_path: '03_Resources/Dead Link Note.md', category: 'Unknown', resolved_path: '' }
        ]
      : title.includes('Artificial')
      ? [
          { title: 'Neural Networks Basics', relative_path: '03_Resources/Neural Networks Basics.md', category: 'Resources', resolved_path: '' },
          { title: 'Machine Learning Ethics', relative_path: '02_Areas/Machine Learning Ethics.md', category: 'Areas', resolved_path: '' }
        ]
      : [
          { title: 'Workout Routines', relative_path: '02_Areas/Workout Routines.md', category: 'Areas', resolved_path: '' },
          { title: 'Nutritional Guidelines', relative_path: '03_Resources/Nutritional Guidelines.md', category: 'Resources', resolved_path: '' }
        ];
    return Promise.resolve({
      project: { title, relative_path: `01_Projects/${title}.md`, category: 'Projects' },
      dependencies: deps
    });
  }
  
  if (cmd === 'preview_stage_bundle') {
    const selectedList = args.selectedDeps.map((d: string) => `- [x] Resolved dependency: ${d}`).join('\n');
    return Promise.resolve(`# Study Guide: ${args.target}\n\nThis is a selectively compiled markdown bundle prepared for your staging dropzone.\n\n## Included Wiki-Link References:\n${selectedList || '- No references selected'}\n\n---\n*Generated by Brain Indexer Staging Command Center.*`);
  }
  
  if (cmd === 'stage_project_bundle') {
    return Promise.resolve(`${args.outDir}/${args.target}_compiled_study_guide.md`);
  }
  
  return Promise.resolve([]);
};

export let openDialog = async (options: any): Promise<string | null> => {
  console.log('Mock opening dialog', options);
  if (options.title.includes('Obsidian')) {
    return '/mock/Obsidian/SecondBrain';
  } else {
    return '/mock/GoogleDrive/Dropzone';
  }
};

// Safe dynamic resolution of @tauri-apps/api when running under the Tauri desktop wrapper
if (typeof window !== 'undefined' && (window as any).__TAURI_METADATA__) {
  import('@tauri-apps/api/tauri').then((tauriCore) => {
    invoke = tauriCore.invoke;
  });
  import('@tauri-apps/api/dialog').then((tauriDialog) => {
    // @ts-ignore
    openDialog = tauriDialog.open;
  });
}
